### ISSUE TITLE
OnBoard Temperature Sensor no longer accessible

### ISSUE THREAD

**Issue by toolboc** [ms-iot/galileo-sdk#121]
In a previous iteration of the SDK, one could access the Onboard Temperature Sensor by performing an analog read across pin -1.  You can find it mentioned in a portion of the removed comments in [44fe4c8164474b3c152857068fd033043120f875].  There was even a cool demo which used this feature up on the [MS-IoT Sample Apps Page](http://ms-iot.github.io/content/SampleApps.htm).  It would be great if this could be leveraged back into the current codebase.

**Comment by ooeygui** [comment]
Thank you for the report. We did remove the sample when we implemented the lightning codebase. The onboard temperature sensor was accessed outside normal Wiring API. We contemplated adding the infrastructure - including a custom API. The Galileo Gen2 does not have this sensor, so we opted to remove the sample and not invest in the infrastructure.

I'm adding the *help wanted* label. If someone wants to add a custom API to access this, then add a sample, we'd be happy to pull it.

**Comment by toolboc** [comment]
ooeygui,

Thanks for the reply.  Lets assume someone was interested in adding a custom API.  Would you be able to share any resources that would aid in development, for example a link to the older codebase that shows how the sendor can be accessed?

**Comment by ooeygui** [comment]
Hi There,
Sorry for the delay in responding. I dug into this a bit more. Before the Lightning release, the Intel driver itself handled the translation from the 'out of band' GPIO pin, which mapped to the temp sensor. When we moved to lightning and eliminated the driver stack, we lost this translation.

There is a temp sensor on the ADC device itself. (http://www.analog.com/static/imported-files/data_sheets/AD7298.pdf). We're looking at adding a method on the AD7298Device class to read this sensor (and sample), which can be used by the caller directly.

There's a task in our current sprint to dive into this.

**Comment by ooeygui** [comment]
Closing this issue. We won't be fixing the onboard temp sensor for the Galileo.
