### ISSUE TITLE
Bluetooth Shield as Master not working

### ISSUE THREAD

**Issue by asebak** [ms-iot/galileo-sdk#127]
It would be nice if the samples page can provide a bluetooth example. I am using this shield http://wiki.iteadstudio.com/BT_Shield_%28Master_Slave%29

I have the same code for a bluetooth master working in the ardunio environment and it's working perfectly fine.  When I port the same code to the intel galileo on the windows image it seems the serial data is always empty it sure return something like "+OK".

**Comment by ooeygui** [comment]
Thank you for reaching out. I'll try to get the shield and see what's happening. (this will be difficult as we cannot purchase from iteadstudio.com due to their payment processor; I'll try to find an alternative source)

**Comment by asebak** [comment]
It doesnt have to be the exact shield but any bluetooth module that will act as a master.

**Comment by ooeygui** [comment]
Hi there,
I'm going to close this issue as we are not adding new features to the Galileo program per http://ms-iot.github.io/content/Faqs.htm#galileo. We are directing people to Windows 10 core. Bluetooth is not supported at the moment, but will be in the near future.

Thank you!
Lou
