### ISSUE TITLE
attachInterrupt doesn't call interrupts

### ISSUE THREAD

**Issue by nishanthkarthik** [ms-iot/galileo-sdk#130]
attachInterrupt(0, dmpDataReady, RISING);
I have connected Pin 0 - RX to MPU-6050's INT pin. The interrupt is not called at all. Are there any limitations on what pins I can use for interrupts? I assumed, since the interrupt was just polling, any Pin can be put into the attachInterrupt().

**Comment by nishanthkarthik** [comment]
The software interrupt just digitalReads the pin. If the attached device works at 3.3V, can the polling mechanism still find out the spike?

**Comment by ooeygui** [comment]
Sorry for the delay in responding. 3.3V is not enough to drive the pin. You'll either need to run the board at 3.3v or use a level converter.

**Comment by nishanthkarthik** [comment]
@ooeygui  Will we have hardware interrupt support on galileo while running windows?
