### ISSUE TITLE
Pin mode INPUT_FAST or OUTPUT_FAST

### ISSUE THREAD

**Issue by sokart** [ms-iot/galileo-sdk#133]
I am working with ultrasonic distance sensors and they require the feature of INPUT_FAST or OUTPUT_FAST pin mode (http://bigdinotech.com/tutorials/galileo-tutorials/using-ultrasonic-ping-sensor-with-intel-galileo-and-edison/). The current galileo sdk for Windows IoT doesn't support it. Is there any reason for that?

**Comment by ooeygui** [comment]
Windows for Galileo uses a different model for IO - eliminating the need for explicit fast/slow. As long as you use the SOC pins, you'll get super fast IO.
